public enum AnimationsHumanoidWeaponsEnum
{
	EquipWeapon_Right,
	UnequipWeapon_Right,
	EquipWeapon_Left,
	UnequipWeapon_Left,
	Ranged_HarmonicaRevolver_Hold_Right,
	Ranged_HarmonicaRevolver_Shoot_Right,
	Ranged_HarmoniceRevolver_InsertCartridge_Right,
	Ranged_HarmoniceRevolver_PushCartridge_Right,
	Ranged_HarmonicaRevolver_Hold_Left,
	Ranged_HarmonicaRevolver_Shoot_Left,
	Ranged_HarmoniceRevolver_InsertCartridge_Left,
	Ranged_HarmoniceRevolver_PushCartridge_Left,
	LegKick
}