public enum AnimationsHumanoidWeaponsEnum
{
	EquipWeapon_Right,
	UnequipWeapon_Right,
	EquipWeapon_Left,
	UnequipWeapon_Left,
	Ranged_Revolver_Hold_Right,
	Ranged_Revolver_Shoot_Right,
	Ranged_Revolver_ReloadInsert_Right,
	Ranged_Revolver_ReloadPush_Right,
	Ranged_Revolver_Hold_Left,
	Ranged_Revolver_Shoot_Left,
	Ranged_Revolver_ReloadInsert_Left,
	Ranged_Revolver_ReloadPush_Left,
	Equip,
	Uneqiup,
	Hold,
	Shoot,
	Reload,
	LegKick,
	Attack
}