public enum SaveLoadPlayerPrefsEvents
{
	ApplySettingsSectionGeneralPlayerPrefs,
	ApplySettingsSectionControlsPlayerPrefs,
	ApplySettingsSectionGraphicsPlayerPrefs,
	ApplySettingsSectionAudioPlayerPrefs
}
